### ISSUE TITLE
AzureRmResourceGroupDeployment for storage account creation : The response for resource had empty or invalid content

### ISSUE THREAD

**Issue by Rakesh201180** [Azure/azure-resource-manager-schemas#1497] opened 2021-02-09 04:45 UTC
Template file 

`{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "storageAccount_name": {
            "defaultValue": "stcr2130",
            "type": "String"
        }
    },
    "variables": {},
    "resources": [
        {
            "type": "Microsoft.Storage/storageAccounts",
            "apiVersion": "2019-04-01",
            "name": "[parameters('storageAccount_name')]",
            "location": "southeastasia",
            "tags": {
                "Application": "STACR",
                "Purpose": "fileprocess",
                "AIRID": "2139"
            },
            "sku": {
                "name": "Standard_LRS",
                "tier": "Standard"
            },
            "kind": "StorageV2",
            "properties": {
                "supportsHttpsTrafficOnly": true,
                "encryption": {
                    "services": {
                        "file": {
                            "enabled": true
                        },
                        "blob": {
                            "enabled": true
                        }
                    },
                    "keySource": "Microsoft.Storage"
                },
                "accessTier": "Hot"
            }
        },
        {
            "type": "Microsoft.Storage/storageAccounts/blobServices",
            "apiVersion": "2019-04-01",
            "name": "[concat(parameters('storageAccount_name'), '/default')]",
            "dependsOn": [
                "[resourceId('Microsoft.Storage/storageAccounts', parameters('storageAccount_name'))]"
            ],
            "properties": {
                "cors": {
                    "corsRules": []
                },
                "deleteRetentionPolicy": {
                    "enabled": false
                }
            }
        }
    ]
}`

Getting below error

```
New-AzureRmResourceGroupDeployment : 10:01:30 AM - Resource Microsoft.Storage/storageAccounts 'stcr2130' failed with message '{
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The response for resource had empty or invalid content."
  }
}'
At line:1 char:1
+ New-AzureRmResourceGroupDeployment -ResourceGroupName $resourcegroup  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCmdlet
```

**Comment by jbockle** [comment] 2021-02-24 16:50
we are seeing the same issue for storage accounts, this template worked properly before

```
{
    "status": "Failed",
    "error": {
        "code": "ResourceDeploymentFailure",
        "message": "The response for resource had empty or invalid content."
    }
}
```

```
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "storageName": {
            "type": "String"
        },
        "storageSku": {
            "type": "String"
        },
        "fileShares": {
            "defaultValue": [],
            "type": "Array"
        },
        "ipRules": {
            "type": "Array"
        },
        "virtualNetworkRules": {
            "type": "Array"
        }
    },
    "variables": {
        "shareWorkaround": {
            "true": "[parameters('fileShares')]",
            "false": [
                {
                    "name": "workaround",
                    "quota": 1
                }
            ]
        },
        "fileShares": "[variables('shareWorkaround')[string(greater(length(parameters('fileShares')),0))]]"
    },
    "resources": [
        {
            "type": "Microsoft.Storage/storageAccounts",
            "apiVersion": "2019-06-01",
            "name": "[parameters('storageName')]",
            "location": "[resourceGroup().location]",
            "tags": {},
            "sku": {
                "name": "[parameters('storageSku')]"
            },
            "kind": "StorageV2",
            "properties": {
                "accessTier": "Hot",
                "networkAcls": {
                    "bypass": "AzureServices",
                    "defaultAction": "Deny",
                    "copy": [
                        {
                            "name": "ipRules",
                            "count": "[length(parameters('ipRules'))]",
                            "input": {
                                "value": "[parameters('ipRules')[copyIndex('ipRules')]]",
                                "action": "Allow"
                            }
                        },
                        {
                            "name": "virtualNetworkRules",
                            "count": "[length(parameters('virtualNetworkRules'))]",
                            "input": {
                                "id": "[parameters('virtualNetworkRules')[copyIndex('virtualNetworkRules')]]",
                                "action": "Allow"
                            }
                        }
                    ]
                }
            }
        },
        {
            "type": "Microsoft.Storage/storageAccounts/fileServices/shares",
            "apiVersion": "2019-06-01",
            "name": "[concat(parameters('storageName'), '/default/', variables('fileShares')[copyIndex()].name)]",
            "dependsOn": [
                "[resourceId('Microsoft.Storage/storageAccounts', parameters('storageName'))]"
            ],
            "properties": {
                "shareQuota": "[variables('fileShares')[copyIndex()].quota]"
            },
            "copy": {
                "name": "fileShares",
                "count": "[length(variables('fileShares'))]"
            },
            "condition": "[greater(length(parameters('fileShares')),0)]"
        }
    ]
}
```

**Comment by jbockle** [comment] 2021-02-24 18:38
I was able to fix my template, the subnets in this new subscription needed storage service endpoints added before the acl could be created, maybe this error is just stating some pre-req is required and was not found.  Still, I think the error should probably be improved.  @Rakesh201180 , since you aren't using network acls, maybe confirm the storage account provider is added to the subscription.  I'm not sure what other pre-reqs there would be for storage.

**Comment by mauriciojost** [comment] 2021-07-05 21:57
Same clueless issue being experienced here.

**Comment by anthony-c-martin** [comment] 2021-11-02 13:31
The storage RP team has confirmed that this has since been fixed - closing.

**Closed by anthony-c-martin** 2021-11-02 13:31 UTC
Labels: RP:Storage, Service Issue (Not Schemas)
