### ISSUE TITLE
Schema for Microsoft.ApiManagement/service/templates incorrect

### ISSUE THREAD

**Issue by kenmuse** [Azure/azure-resource-manager-schemas#2176] opened 2022-01-13 05:42 UTC
The schema restricts template names to starting with names which have a lowercase first letter:
https://github.com/Azure/azure-resource-manager-schemas/blob/109fd9f952bcb454c3e49490940796c977d36ba5/schemas/2021-08-01/Microsoft.ApiManagement.json#L2375-L2389
However, the service will report a 404 NotFound error when attempting to create or modify resources using these names. Each name must start with an uppercase letter to be accepted. Exporting an ARM template for an APIM resource will also show this issue; the names will start with an uppercase letter. 
This also causes a problem defining the resources with Bicep templates. Those templates enforce the schema restrictions.

**Comment by anthony-c-martin** [comment] 2022-01-13 14:48
Thanks for reporting this! I've raised https://github.com/Azure/azure-rest-api-specs/issues/17340 to track the root cause. Once fixed, schemas & bicep types will be automatically updated - closing this issue.

**Closed by anthony-c-martin** 2022-01-13 14:48 UTC
Labels: Needs: Triage :mag_right:
