### ISSUE TITLE
Schema is missing for resource Microsoft.KeyVault/vaults with apiVersion "2019-09-01"

### ISSUE THREAD

**Issue by Yvand** [Azure/azure-resource-manager-schemas#1195] opened 2020-09-11 08:05 UTC
The resource reference for apiVersion "2019-09-01" is documented here:
https://docs.microsoft.com/en-us/azure/templates/Microsoft.KeyVault/2019-09-01/vaults
Is it possible to add its corresponding schema?

**Comment by michal-halenka-datasentics** [comment] 2020-09-28 10:11
This is probably duplicate of #759

**Comment by anthony-c-martin** [comment] 2020-12-08 04:11
FWIW we could probably onboard KeyVault for [automatic schema generation](https://github.com/Azure/azure-resource-manager-schemas/tree/master/generator#onboarding-teams-to-autogeneration-pipeline) once https://github.com/Azure/azure-rest-api-specs/pull/11964 has been merged.

**Comment by anthony-c-martin** [comment] 2021-09-27 20:47
Fixed by #1525

**Closed by anthony-c-martin** 2021-09-27 20:47 UTC
Labels: RP:KeyVault
