### ISSUE TITLE
Microsoft.KeyVault/vaults missing schema for version 2018-02-14

### ISSUE THREAD

**Issue by neilpeterson** [Azure/azure-resource-manager-schemas#853] opened 2020-01-30 22:35 UTC
https://github.com/Azure/azure-rest-api-specs/tree/master/specification/keyvault/resource-manager/Microsoft.KeyVault/stable/2018-02-14

Reported in ARM tools - https://github.com/microsoft/vscode-azurearmtools/issues/461

**Comment by DrBushyTop** [comment] 2020-02-13 09:02
Not sure if this will get fixed along side the main vaults resource, but "Microsoft.KeyVault/vaults/secrets"  is also missing the same apiVersion 2018-02-14.

**Comment by jkruis** [comment] 2020-03-03 10:21
Duplicate of #759

**Closed** 2020-03-03 16:36 UTC
Labels: RP Fix, RP:KeyVault
